---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-read-only-user
  namespace: 01-05
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dashboard-read-only-role
  namespace: 01-05
rules:
- apiGroups:
  - "*"
  resources:
  - jobs
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dashboard-read-only-binding
  namespace: 01-05
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dashboard-read-only-role
subjects:
- kind: ServiceAccount
  name: dashboard-read-only-user
  namespace: 01-05
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: list-nodes-and-namespaces
rules:
- apiGroups:
  - "*"
  resources:
  - nodes
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-list-nodes-and-namespaces
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: list-nodes-and-namespaces
subjects:
- kind: ServiceAccount
  name: dashboard-read-only-user
  namespace: 01-05
