---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: "01-03"
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: ckss.local
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: foo-service
            port:
              number: 5678
  - http:
      paths:
      - pathType: ImplementationSpecific
        path: /
        backend:
          service:
            name: bar-service
            port:
              number: 5678
  tls:
  - hosts:
    - ckss.local
    secretName: ckss-local-tls
